; PlatformIO Project Configuration File
;
; Build options: build flags, source filter
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
#upload_protocol = espota
#upload_port = 192.168.42.243
platform = espressif32
board = nodemcu-32s
framework = arduino
build_flags =
    -D DEBUG_LOG_ENABLE=0
    -D WIFI_CONFIG=2
lib_deps =
    fortyseveneffects/MIDI Library@^5.0.2
    max22/ESP32-BLE-MIDI@^0.3.2
    lathoub/AppleMIDI@^3.3.0
    igorantolic/Ai Esp32 Rotary Encoder@^1.7
    arduinogetstarted/ezLED@^1.0.1

[env:LEDController]
extends = common
build_src_filter = +<*> -<*.relay.cpp>
build_flags =
    ${common.build_flags}
    -D LEDCONTROLLER
lib_deps =
    ${common.lib_deps}
    fastled/FastLED@^3.10.3

[env:RelayController]
extends = common
build_src_filter = +<*> -<*.led.cpp>
build_flags =
    ${common.build_flags}
    -D RELAYCONTROLLER
lib_deps =
    ${common.lib_deps}
    arduinogetstarted/ezButton @ ^1.0.6