; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:LEDController]
platform = espressif32
board = nodemcu-32s
framework = arduino
build_src_filter = +<*> -<*.schuko.cpp>
build_flags = -D LEDCONTROLLER
upload_protocol = espota
#upload_protocol = espota
#upload_port = 192.168.42.243
lib_deps = 
	fastled/FastLED@^3.10.1
	fortyseveneffects/MIDI Library@^5.0.2
	max22/ESP32-BLE-MIDI@^0.3.2
	igorantolic/Ai Esp32 Rotary Encoder@^1.7
	arduinogetstarted/ezLED@^1.0.1

[env:SchukoController]
platform = espressif32
board = nodemcu-32s
build_src_filter = +<*> -<*.led.cpp>
framework = arduino
build_flags = -D SCHUKOCONTROLLER
#upload_protocol = espota
#upload_port = 192.168.42.243
lib_deps =
	fortyseveneffects/MIDI Library@^5.0.2
	max22/ESP32-BLE-MIDI@^0.3.2
	igorantolic/Ai Esp32 Rotary Encoder@^1.7
	arduinogetstarted/ezLED@^1.0.1